### ISSUE TITLE
Audio still clicks when restarting after a rest block

### ISSUE THREAD

**Issue by hyperobject** [LLK/scratch-audioengine#93] opened 2018-06-19 18:36 UTC
### Expected behavior
Audio should fade out rather than producing clicks.

### Actual behavior
Sometimes audio still produces clicks when starting and stopping sounds after a 'rest for (n) beats'
 

### Steps to reproduce
Upload [chords_clicking_sb3.zip (actually an sb3 file)](https://github.com/LLK/scratch-audio/files/2116445/chords_clicking_sb3.zip) to the Scratch 3.0 preview and run the script. The audio should have clicks in it when restarting the loop.

### Operating system and browser
Chromebook Chrome 67, macOS 10.13.5 Firefox Nightly 62

**Comment by mzgoddard** [comment] 2018-06-20 18:57
This is likely a duplicate of #42.

**Comment by mzgoddard** [comment] 2018-06-20 18:57
#89 should fix this.

**Comment by thisandagain** [comment] 2018-06-20 19:04
Tracking in #42

**Closed as completed by thisandagain** 2018-06-20 19:04 UTC
Labels: bug
