### ISSUE TITLE
"The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page." are displayed in chrome console when scratch is started. 

### ISSUE THREAD

**Issue by marron9999** [LLK/scratch-audioengine#151] opened 2021-05-08 05:33 UTC
### Expected behavior

Using chrome, and open https://scratch.mit.edu/projects/editor/ 

### Operating system and browser

Windows 10, 20H2, Chrome 90

First message: 

> new AudioContext()   in AudioEngine.js:44

Second time, after that: 

> Destination called by StartAudioContext(this.audioContext);   in AudioEngine.js:51

The same phenomenon occurs even if scratch-gui is started in the local environment.
It seems to occur in the following places.

node_module/startaudiocontext/StartAudioContext.js

```
	function onStarted(context, callback){

		function checkLoop(){
			if (isStarted(context)){
				callback()
			} else {
				requestAnimationFrame(checkLoop)
				if (context.resume){
===>					context.resume()
				}
			}
		}

		if (isStarted(context)){
			callback()
		} else {
			checkLoop()
		}
	}
```

**Comment by apple502j** [comment] 2021-05-08 14:00
Duplicate of LLK/scratch-gui#4514

**Closed as completed** 2021-05-13 17:29 UTC
