### ISSUE TITLE
Pan left/right doesn't effect extension blocks

### ISSUE THREAD

**Issue by 2br-2b** [LLK/scratch-audioengine#121] opened 2020-07-21 13:23 UTC
### Expected Behavior

[When green flag clicked
set [pan left/right v] effect to (100)
play note (60) for (0.25) beats
speak (hello)](https://scratchblocks.github.io/#?style=scratch3&script=When%20green%20flag%20clicked%0Aset%20%5Bpan%20left%2Fright%20v%5D%20effect%20to%20(100)%0Aplay%20note%20(60)%20for%20(0.25)%20beats%0Aspeak%20(hello))

(I would post a Scratch blocks image, but Github isn't letting me upload the image)

All of the sound should play through the right speaker.

### Actual Behavior

The sound plays equally through both speakers.

The pan left/right causes surround sound, and should move all sound played to only the left/right speaker at 100%. However, this only works with the Sounds blocks, and not with other sound-playing blocks.

### Steps to Reproduce

Build the listed code in Scratch,

### Operating System and Browser

Linux Mint, Firefox

Same issue as LLK/scratch-gui#6015 and likely the same issue as LLK/scratch-audio#18

**Comment by BryceLTaylor** [comment] 2020-07-21 20:33
This is a duplicate of https://github.com/LLK/scratch-vm/issues/2526

**Closed as completed by BryceLTaylor** 2020-07-21 20:33 UTC
